spring:
 application:
  name: frontend

server:
  port: 8080

eureka:
  instanse:
    hostname: frontend
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF