spring:
 application:
  name: feign-simple-server

server:
  port: 8777

eureka:
  instanse:
    hostname: feign--simple-server
  client:
   serviceUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF