spring:
 application:
  name: message-service

server:
  port: 9000

eureka:
  instanse:
    hostname: message-service
  client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
     healthcheck:
        enabled: true

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF