spring:
 application:
  name: sn-message-service

server:
  port: 8701

eureka:
  instanse:
    hostname: sn-message-service
  client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
     healthcheck:
        enabled: true

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF