spring:
 application:
  name: image-service

server:
  port: 8015

eureka:
  instanse:
    hostname: image-service
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF