spring:
 application:
  name: feign-simple-client

server:
  port: 8778

eureka:
  instanse:
    hostname: feign--simple-client
  client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
     healthcheck:
        enabled: true

feign:
  hystrix:
    enabled: true

#turbine:
#  aggregator:
#    clusterConfig: FEIGN-SIMPLE-CLIENT

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF