spring:
 application:
  name: gateway-service

server:
  port: 8080

zuul:
  routes:
    gateway:
      path: /gateway/**
      url: http://${DISCOVERY_HOST:localhost}:8761

eureka:
  instanse:
    hostname: gateway-service
  client:
   serviceUrl:
        defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/